# Day 3 Assignment

# Questions 1:
Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [1]:
import numpy as np
arr=np.arange(2,50,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


# Questions 2:
Accept two lists of 5 elements each from the user. Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [3]:
a=np.array([int(input()) for i in range(5)])
b=np.array([int(input()) for i in range(5)])
print(np.sort(np.concatenate((a,b))))

2
1
4
8
7
9
3
4
11
0
[ 0  1  2  3  4  4  7  8  9 11]


# Questions 3:
Write a code snippet to find the dimensions of a ndarray and its size.

In [4]:
arr=np.array([1,2,3,4,5,6])
print(arr.ndim)
print(arr.size)

1
6


# Questions 4:
How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet Hint: np.newaxis, np.expand_dims

In [8]:
# create 1D numpy array from a list
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print('1D Numpy array:')
print(arr)
print("\n")

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# Convert 1D array to a 2D numpy array of 2 rows and 3 columns
arr_2d = np.reshape(arr, (2, 5))
print("2D Array ")
print(arr_2d)

1D Numpy array:
[0 1 2 3 4 5 6 7 8 9]


2D Array 
[[0 1 2 3 4]
 [5 6 7 8 9]]


# Questions 5:
Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()

In [9]:
a = np.array([[1, 2], 
              [3, 4]]) 
  
b = np.array([[5, 6], 
              [7, 8]]) 
  
# vertical stacking 
print("Vertical stacking:\n", np.vstack((a, b))) 
  
# horizontal stacking 
print("\nHorizontal stacking:\n", np.hstack((a, b)))

Vertical stacking:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontal stacking:
 [[1 2 5 6]
 [3 4 7 8]]


# Questions 6:
How to get unique items and counts of unique items?

In [11]:
def unique(list1): 
    x = np.array(list1) 
    print(np.unique(x)) 
      
# driver code 
list1 = [10, 20, 10, 30, 40, 40] 
print("The unique values from 1st list is") 
unique(list1) 
  
# converting our list to set 
new_set = set(list1) 
print("No of unique items in the list are:", len(new_set))

The unique values from 1st list is
[10 20 30 40]
No of unique items in the list are: 4
